name: Avro Compatibility Tests
on:
  push:
    tags: ["**"]
    branches:
      - master
  pull_request:
jobs:
  test:
    name: "Compatibility: avro ${{ matrix.avro }}/gradle ${{ matrix.gradle }}"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        avro: ["1.12.1"]
        gradle: ["8.4", "8.14.4"]
        java: ["17"]
    steps:
      - uses: actions/checkout@v6
      - uses: bakdata/ci-templates/actions/java-gradle-setup@1.77.0
        with:
          java-version: ${{ matrix.java }}
      - shell: bash
        run: ./gradlew testCompatibility -PavroVersion=${{ matrix.avro }} -PgradleVersion=${{ matrix.gradle }}
