name: Gradle Compatibility Tests
on:
  push:
    tags: ["**"]
    branches:
      - master
  pull_request:
jobs:
  test:
    name: "Compatibility: gradle ${{ matrix.gradle }}/java ${{ matrix.java }}"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        avro: ["1.12.1"]
        gradle: [
          "8.4", "8.5", "8.6", "8.7", "8.8", "8.9", "8.10", "8.10.1", "8.10.2", "8.11", "8.11.1", "8.12", "8.12.1", "8.13", "8.14", "8.14.1", "8.14.2", "8.14.3", "8.14.4"
          # See here for latest versions: https://services.gradle.org/versions/
        ]
        java: ["17"]
    steps:
      - uses: actions/checkout@v6
      - uses: bakdata/ci-templates/actions/java-gradle-setup@1.77.0
        with:
          java-version: ${{ matrix.java }}
      - shell: bash
        run: ./gradlew testCompatibility -PavroVersion=${{ matrix.avro }} -PgradleVersion=${{ matrix.gradle }}
