# See https://docs.gradle.org/current/userguide/compatibility.html
name: Java Compatibility Tests
on:
  push:
    tags: ["**"]
    branches:
      - master
  pull_request:
jobs:
  test:
    name: "Compatibility: java ${{ matrix.java }}/gradle ${{ matrix.gradle }}"
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        avro: ["1.12.1"]
        gradle: ["8.4", "8.14.4"] # See here for latest versions: https://services.gradle.org/versions/
        java: ["17", "18", "19", "20", "21", "22", "23", "24"]
        exclude:
          - java: "22"
            gradle: "8.4"
          - java: "23"
            gradle: "8.4"
          - java: "24"
            gradle: "8.4"
        include:
          - java: "22"
            gradle: "8.7"
            avro: "1.12.1"
            distribution: "zulu"
          - java: "23"
            gradle: "8.10"
            avro: "1.12.1"
            distribution: "zulu"
          - java: "24"
            gradle: "8.14"
            avro: "1.12.1"
            distribution: "zulu"
          - java: "17"
            distribution: "temurin"
          - java: "18"
            distribution: "zulu"
          - java: "19"
            distribution: "zulu"
          - java: "20"
            distribution: "zulu"
          - java: "21"
            distribution: "temurin"
          - java: "22"
            distribution: "zulu"
          - java: "23"
            distribution: "zulu"
          - java: "24"
            distribution: "zulu"
    steps:
      - uses: actions/checkout@v6
      - uses: bakdata/ci-templates/actions/java-gradle-setup@1.77.0
        with:
          java-distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}
      - shell: bash
        run: ./gradlew testCompatibility -PavroVersion=${{ matrix.avro }} -PgradleVersion=${{ matrix.gradle }}
