# See https://docs.gradle.org/current/userguide/compatibility.html
name: Java Compatibility Tests
on:
  push:
    tags: ["**"]
    branches:
      - master
  pull_request:
jobs:
  java17:
    name: "Compatibility: java ${{ matrix.java }}/gradle ${{ matrix.gradle }}"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        avro: ["1.11.0"]
        gradle: ["7.3", "8.14.4"] # See here for latest versions: https://services.gradle.org/versions/
        java: ["17"]
    steps:
      - uses: actions/checkout@v6
      - uses: bakdata/ci-templates/actions/java-gradle-setup@feature/repo-branch
        with:
          java-version: ${{ matrix.java }}
      - shell: bash
        run: ./gradlew testCompatibility -PavroVersion=${{ matrix.avro }} -PgradleVersion=${{ matrix.gradle }}
  java18:
    name: "Compatibility: java ${{ matrix.java }}/gradle ${{ matrix.gradle }}"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        avro: ["1.11.0"]
        gradle: ["7.5", "8.14.4"] # See here for latest versions: https://services.gradle.org/versions/
        java: ["18"]
    steps:
      - uses: actions/checkout@v6
      - uses: bakdata/ci-templates/actions/java-gradle-setup@feature/repo-branch
        with:
          java-distribution: "zulu"
          java-version: ${{ matrix.java }}
      - shell: bash
        run: ./gradlew testCompatibility -PavroVersion=${{ matrix.avro }} -PgradleVersion=${{ matrix.gradle }}
  java-19:
    name: "Compatibility: java ${{ matrix.java }}/gradle ${{ matrix.gradle }}"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        avro: ["1.11.0"]
        gradle: ["7.6", "8.14.4"] # See here for latest versions: https://services.gradle.org/versions/
        java: ["19"]
    steps:
      - uses: actions/checkout@v6
      - uses: bakdata/ci-templates/actions/java-gradle-setup@feature/repo-branch
        with:
          java-distribution: "zulu"
          java-version: ${{ matrix.java }}
      - shell: bash
        run: ./gradlew testCompatibility -PavroVersion=${{ matrix.avro }} -PgradleVersion=${{ matrix.gradle }}
  java-20:
    name: "Compatibility: java ${{ matrix.java }}/gradle ${{ matrix.gradle }}"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        avro: ["1.11.0"]
        gradle: ["8.1", "8.14.4"] # See here for latest versions: https://services.gradle.org/versions/
        java: ["20"]
    steps:
      - uses: actions/checkout@v6
      - uses: bakdata/ci-templates/actions/java-gradle-setup@feature/repo-branch
        with:
          java-distribution: "zulu"
          java-version: ${{ matrix.java }}
      - shell: bash
        run: ./gradlew testCompatibility -PavroVersion=${{ matrix.avro }} -PgradleVersion=${{ matrix.gradle }}
  java-21:
    name: "Compatibility: java ${{ matrix.java }}/gradle ${{ matrix.gradle }}"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        avro: ["1.11.0"]
        gradle: ["8.4", "8.14.4"] # See here for latest versions: https://services.gradle.org/versions/
        java: ["21"]
    steps:
      - uses: actions/checkout@v6
      - uses: bakdata/ci-templates/actions/java-gradle-setup@feature/repo-branch
        with:
          java-version: ${{ matrix.java }}
      - shell: bash
        run: ./gradlew testCompatibility -PavroVersion=${{ matrix.avro }} -PgradleVersion=${{ matrix.gradle }}
  java-22:
    name: "Compatibility: java ${{ matrix.java }}/gradle ${{ matrix.gradle }}"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        avro: ["1.11.0"]
        gradle: ["8.7", "8.14.4"] # See here for latest versions: https://services.gradle.org/versions/
        java: ["22"]
    steps:
      - uses: actions/checkout@v6
      - uses: bakdata/ci-templates/actions/java-gradle-setup@feature/repo-branch
        with:
          java-distribution: "zulu"
          java-version: ${{ matrix.java }}
      - shell: bash
        run: ./gradlew testCompatibility -PavroVersion=${{ matrix.avro }} -PgradleVersion=${{ matrix.gradle }}
  java-23:
    name: "Compatibility: java ${{ matrix.java }}/gradle ${{ matrix.gradle }}"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        avro: ["1.11.0"]
        gradle: ["8.10", "8.14.4"] # See here for latest versions: https://services.gradle.org/versions/
        java: ["23"]
    steps:
      - uses: actions/checkout@v6
      - uses: bakdata/ci-templates/actions/java-gradle-setup@feature/repo-branch
        with:
          java-distribution: "zulu"
          java-version: ${{ matrix.java }}
      - shell: bash
        run: ./gradlew testCompatibility -PavroVersion=${{ matrix.avro }} -PgradleVersion=${{ matrix.gradle }}
  java-24:
    name: "Compatibility: java ${{ matrix.java }}/gradle ${{ matrix.gradle }}"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        avro: ["1.11.0"]
        gradle: ["8.14", "8.14.4"] # See here for latest versions: https://services.gradle.org/versions/
        java: ["24"]
    steps:
      - uses: actions/checkout@v6
      - uses: bakdata/ci-templates/actions/java-gradle-setup@feature/repo-branch
        with:
          java-distribution: "zulu"
          java-version: ${{ matrix.java }}
      - shell: bash
        run: ./gradlew testCompatibility -PavroVersion=${{ matrix.avro }} -PgradleVersion=${{ matrix.gradle }}
