name: OS Compatibility
on:
  push:
    tags: ["**"]
    branches:
      - master
  pull_request:
jobs:
  build:
    name: "Compatibility: ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [17] # Minimum supported major version
        os: [ubuntu-latest, windows-latest, macOS-latest] # All supported OS
    steps:
      - uses: actions/checkout@v6
      - uses: bakdata/ci-templates/actions/java-gradle-setup@1.75.0
        with:
          java-version: ${{ matrix.java }}
      - shell: bash
        run: ./gradlew test
